import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ContentEngine — AI That Runs Your Social Media",
  description:
    "AI-powered social media content generation platform. Get a full week of platform-optimized posts in seconds. Start your 7-day free trial today.",
  keywords: [
    "social media AI",
    "content generation",
    "AI copywriting",
    "social media automation",
    "marketing AI",
  ],
  openGraph: {
    title: "ContentEngine — AI That Runs Your Social Media",
    description:
      "Get a full week of platform-optimized social media posts generated by AI in seconds. Start free.",
    type: "website",
    locale: "en_US",
    siteName: "ContentEngine",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} antialiased min-h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
